### PR TITLE
Fixed django.utils.simplejson deprecation warning

### PR DESCRIPTION
**Pull request by iepathos**
Fixed deprecation warning for django1.6 with try/except import json as simplejson
Warning was:
lib/python2.7/site-packages/zebra/views.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

### CODE REVIEW

**Comment by josema-xyz** [comment]
Hey everybody! How is this issue going?

**Comment by iepathos** [comment]
Hi, not sure why this hasn't been pulled up yet, very small adaptive import change which completely solves the deprecation warning.  You can go ahead and copy the changes to your django-zebra views.py lib to remove the warnings yourself or clone off this repo https://github.com/iepathos/django-zebra till changes are pulled through.

**Comment by jarcoal** [comment]
Sorry this repo isn't well monitored right now.  I will merge this in and maybe @skoczen can push up a new version to pypi.

**Comment by skoczen** [comment]
@jarcoal Given that I'm the blocker most of the time to progress on this, I'd love to do better - can you and @leetrout email me at (my username at gmail) or post your pypi usernames, and I'll add you as maintainers so you can push out new releases?

**Comment by leetrout** [comment]
Same username on pypi. Thanks, Steven.

**Comment by skoczen** [comment]
You're all set, Lee - thanks for grabbing it!

**Comment by skoczen** [comment]
Also, @jarcoal, since there's someone with your username on pypi and appears to be you, I'm adding `jarcoal` as well - ping me if that's not you.

Thanks, folks!

**Pull request merged**
