### PR TITLE
Death to copy & paste.

### PR DESCRIPTION
**Pull request by danawoodman**
Fixing docstring to account for mislabeled properties.

### CODE REVIEW

**Comment by leetrout** [comment]
Heh, guilty as charged. But you need to update the lines following your changes in order to be accurate.

Would you care to do that and add the changes to this PR?

**Comment by danawoodman** [comment]
Think that should be it, no?

Don't worry, we're all guilty of such crimes once and a while ;)

**Comment by leetrout** [comment]
There's actually a lot wrong with all of those doc strings.... I just realized all of them say they add the property `stripe` but only the top one does.

Face Palm

**Comment by danawoodman** [comment]
We'll at least now you know of all your faults and you can address them :P

I'm still oblivious to most of mine...

**Comment by leetrout** [comment]
Haha, yea.  Would you care to checkout PR 13 https://github.com/GoodCloud/django-zebra/pull/13 and let me know if something else jumps out at you?

I grabbed your changes with `git pull git://github.com/danawoodman/django-zebra.git patch-1`

**Pull request closed without merging**
